# Generated by Django 5.1.6 on 2025-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='recipes',
            index=models.Index(fields=['-time_create'], name='recipes_rec_time_cr_d08964_idx'),
        ),
    ]
