# Generated by Django 5.1.6 on 2025-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
