# Generated by Django 5.1.6 on 2025-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
    ]
